version = 0.1
[default.deploy.parameters]
stack_name = "grocery-shopping-dotnet"
resolve_s3 = true
s3_prefix = "grocery-shopping-dotnet"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
